### ISSUE TITLE
Theme not compiling

### ISSUE THREAD

**Issue by Ozuhan** [AccraZed/YoRHA-UI-BetterDiscord#2]
I tried to install the 1.3.1, 1.3 and 1.2 theme and it seems like the file don't want to compile on Discord. I joined a screenshot of the error message, every version gives the same error message
![Discord_DBk4KxclFn](https://user-images.githubusercontent.com/19546270/56643446-f0e31280-6679-11e9-89a5-14831b65179b.png)

**Comment by Darkenend** [comment]
This is fixed easily with the addition of a Meta line
```css
//META{"name":"YoRHA-UI","description":"Better Discord theme based around NieR: Automata's Menu UI","author":"AccraZed","version":"1.3.1"}*//{}
```

**Comment by Ozuhan** [comment]
Thank you for your answer Darkenend. I added your line at the top of the file I downloaded in the release section and now the message changed to "META could not be parsed" instead of "Not found" but the theme still doesn't work

**Comment by Darkenend** [comment]
I have that exact line so I'm not sure, you have the curly brackets at the end of the line? I'm sure it won't work if you don't have them.

**Comment by Ozuhan** [comment]
Yes, I basically copied and pasted your line in my file
![image](https://user-images.githubusercontent.com/19546270/56692883-70f19280-66e3-11e9-9b04-1302c5429fe9.png)

**Comment by Darkenend** [comment]
Paste it all in one line, that's how I have it.

**Comment by Ozuhan** [comment]
That was it, seems like Visual Studio fucked up my copy/paste. The theme doesn't work as it should though, but I guess it might be more related to the new Discord update than a problem on the theme itself. Thanks for your help.
